import zipfile
import unrar

#some parts of the code were generated by clyde's ai

def descomprimir_zip(ruta_archivo):
    with zipfile.ZipFile(ruta_archivo, 'r') as archivo_zip:
        for nombre_archivo in archivo_zip.namelist():
            print(f"Descomprimiendo: {nombre_archivo}")
            archivo_zip.extract(nombre_archivo)

def descomprimir_rar(ruta_archivo):
    with unrar.RarFile(ruta_archivo, 'r') as archivo_rar:
        for nombre_archivo in archivo_rar.namelist():
            print(f"Descomprimiendo: {nombre_archivo}")
            archivo_rar.extract(nombre_archivo)

tipo_archivo = input("""
Seleccione una opción:

[1] zip
[2] rar

Github: https://github.com/Scripter928
        
""")
ruta_archivo = input("Ingrese la ruta del archivo: ")

if tipo_archivo == "zip":
    descomprimir_zip(ruta_archivo)
elif tipo_archivo == "rar":
    descomprimir_rar(ruta_archivo)
else:
    print("Tipo de archivo no válido. Por favor, elija 'zip' o 'rar'.")
